version: '3'
services:
    db:
        container_name: db
        image: postgres:9.6.7-alpine
        volumes:
            - ./init_users.sql:/docker-entrypoint-initdb.d/init_users.sql
            - ./init_products.sql:/docker-entrypoint-initdb.d/init_products.sql
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 30s
            retries: 3

    users:
        container_name: users
        build: ./user-service/
        volumes:
            - './user-service:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/jungle_users
            - NODE_ENV=${NODE_ENV}
            - TOKEN_SECRET=juNgl3Sc0ut_ch4Llenge
        depends_on:
            - db

    products:
        container_name: products
        build: ./product-service/
        volumes:
            - './product-service:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/jungle_products
            - NODE_ENV=${NODE_ENV}
            - TOKEN_SECRET=juNgl3Sc0ut_ch4Llengee
        depends_on:
            - db
            - users

    web-service:
        container_name: web-service
        build: ./web/
        volumes:
            - './web:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - '3007:3006'
        environment:
            - NODE_ENV=${NODE_ENV}
        depends_on:
            - users
            - products
        links:
            - users
            - products

    swagger:
        container_name: swagger
        build: ./product-service/swagger/
        volumes:
            - './product-service/swagger:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - '3003:3001'
        environment:
            - NODE_ENV=${NODE_ENV}
        depends_on:
            - users
            - products